name: "Check code formatting"

on:
  pull_request:

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Prepare
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository -y 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main'
          sudo apt install clang-format
      - name: Format
        run: |
          find src -iname "*.[h,c]" -exec clang-format -i {} \;
      - name: Check
        run: |
          git status
          git diff --quiet
